# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
# https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SavchenkoDV/buthor.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
