#this is version1 of Vagrantfile in Part 2

Vagrant.configure("2") do |config|
    #This defines a virtual machine within the Vagrant environment and allows you to manage multiple VMs separately.
    #no need to define the only one machine in the project
    #config.vm.define "areggieS" do |server|
    config.vm.box = "ubuntu/jammy64"

    #This sets the hostname inside the guest operating system.
    config.vm.hostname = "areggieS"
    config.vm.network "private_network", ip: "192.168.56.110"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
        
        #This modifies the VirtualBox machine name that appears in the VirtualBox GUI.
        vb.customize ['modifyvm', :id, "--name", "areggieS"]
      end
      server.vm.provision "shell", path: "scripts/part2server.sh"
     end
  